# Demonstrate changing acs, share and proxy ports to 7080, postgres port to 5555, solr6 port to 9999
# This docker-compose file will spin up an ACS cluster on a local host or on a server and it requires a minimum of 8GB Memory to distribute among containers.

version: "3.8"

services:
    alfresco:
        build:
          dockerfile: ./Dockerfile
          context: ./configs-to-override/alfresco
          args:
            ACS_TAG: ${ACS_TAG}
        deploy:
          resources:
            limits:
              memory: 4g
        environment:
            JAVA_TOOL_OPTIONS: "
                -Dencryption.keystore.type=JCEKS
                -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=DESede
                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=oKIWzVdEdA
                -Dmetadata-keystore.metadata.algorithm=DESede
                "
            JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5555/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=9999
                -Dsolr.http.connection.timeout=1000
                -Dsolr.secureComms=secret
                -Dsolr.sharedSecret=secretpassword
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=127.0.0.1
                -Dshare.port=7080
                -Dalfresco.host=localhost
                -Dalfresco.port=7080
                -Daos.baseUrlOverwrite=http://localhost:7080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dlocal.transform.service.enabled=true
                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
                -Dcsrf.filter.enabled=false
                -Dmail.host=smtp
                -Dmail.port=25
                -Dmail.username=anonymous
                -Dmail.password=
                -Dmail.protocol=smtp
                -Dmail.smtps.starttls.enable=false
                -Dmail.smtps.auth=false
                -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
                "
            TZ: "America/New_York"

        volumes:
          #Bind mount SHORT SYNTAX - [SOURCE:]TARGET[:MODE]
          #SOURCE can be a named volume or a (relative or absolute) path on the host system. 
          #TARGET is an absolute path in the container where the volume is mounted. 
          #MODE is a mount option which can be read-only (ro) or read-write (rw) (default).
          #Example: ./data/alfresco/alf_data:/usr/local/tomcat/alf_data/:rw
          - ./data/alfresco/alf_data:/usr/local/tomcat/alf_data
        depends_on:
          - postgres
          - solr6
          
    transform-core-aio:
        image: alfresco/alfresco-transform-core-aio:${TRANSFORMATION_CORE_TAG}
        deploy:
          resources:
            limits:
              memory: 1536m
        environment:
            JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
            TZ: "America/New_York"
        ports:
            - 8090:8090
            
    share:
        build:
          dockerfile: ./Dockerfile
          context: ./configs-to-override/share
          args:
            SHARE_TAG: ${SHARE_TAG}
        deploy:
          resources:
            limits:
              memory: 2g
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "7080"
            JAVA_OPTS: "
                -XX:MinRAMPercentage=50
                -XX:MaxRAMPercentage=80
                -Dalfresco.host=localhost
                -Dalfresco.port=7080
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                "
            TZ: "America/New_York"

    postgres:
        image: postgres:${POSTGRES_TAG}
        deploy:
          resources:
            limits:
              memory: 1g
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
            - PGPORT=5555
            - TZ=America/New_York
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5555:5555
        volumes:
          - ./data/postgres/data:/var/lib/postgresql/data
            
    solr6:
        build:
          dockerfile: ./Dockerfile
          context: ./configs-to-override/solr
          args:
            ASS_TAG: ${ASS_TAG}
        deploy:
          resources:
            limits:
              memory: 2g
        environment:
            # Solr needs to know how to register itself with Alfresco
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "7080"
            #Solr jetty port, to start solr6 on port 9999
            SOLR_PORT: "9999"
            # Alfresco needs to know how to call solr
            SOLR_SOLR_HOST: "solr6"
            SOLR_SOLR_PORT: "9999"
            # Create the default alfresco and archive cores
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms2g -Xmx2g"
            # HTTPS or SECRET
            ALFRESCO_SECURE_COMMS: "secret"
            # SHARED SECRET VALUE
            JAVA_TOOL_OPTIONS: "
              -Dalfresco.secureComms.secret=secretpassword
            "
            TZ: "America/New_York"
            
        ports:
            - 8083:9999 #Browser port
        volumes:
            - ./data/search-services/data:/opt/alfresco-search-services/data
            
    activemq:
        image: alfresco/alfresco-activemq:${AMQ_TAG}
        deploy:
          resources:
            limits:
              memory: 1g
        environment:
            TZ: "America/New_York"
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP

    smtp:
        image: mwader/postfix-relay
        mem_limit: 128m
        
    proxy:
        build:
          dockerfile: ./Dockerfile
          context: ./configs-to-override/proxy
          args:
            NGNIX_TAG: ${NGNIX_TAG}
        deploy:
          resources:
            limits:
              memory: 256m
        depends_on:
            - alfresco
        environment:
            TZ: "America/New_York"
            DISABLE_PROMETHEUS: "true"
            DISABLE_SYNCSERVICE: "true"
            DISABLE_ADW: "true"
        ports:
            - 7080:7080
        links:
            - alfresco
            - share