# Demonstrate changing acs, share and proxy ports to 7080, postgres port to 5555, solr6 port to 9999
# This docker-compose file will spin up an ACS cluster on a local host or on a server and it requires a minimum of 8GB Memory to distribute among containers.

version: "3.8"

services:
    alfresco:
        build:
          dockerfile: ./Dockerfile
          context: ./configs-to-override/alfresco
          args:
            ACS_TAG: ${ACS_TAG}
        deploy:
          resources:
            limits:
              memory: 1500m
        environment:
            CATALINA_OPTS : "-agentlib:jdwp=transport=dt_socket,address=*:7000,server=y,suspend=n"
            JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5555/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=9999
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=127.0.0.1
                -Dshare.port=7080
                -Dalfresco.host=localhost
                -Dalfresco.port=7080
                -Daos.baseUrlOverwrite=http://localhost:7080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE

                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/

                -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/
                -Djodconverter.url=http://transform-core-aio:8090/
                -Dimg.url=http://transform-core-aio:8090/
                -Dtika.url=http://transform-core-aio:8090/
                -Dtransform.misc.url=http://transform-core-aio:8090/
                
                -Dcsrf.filter.enabled=false
                
                -Dmail.host=smtp
                -Dmail.port=25
                -Dmail.username=anonymous
                -Dmail.password=
                -Dmail.protocol=smtp
                -Dmail.smtps.starttls.enable=false
                -Dmail.smtps.auth=false
                
                -Xms1500m -Xmx1500m
                "
            TZ: "America/New_York"

        volumes:
          #Bind mount SHORT SYNTAX - [SOURCE:]TARGET[:MODE]
          #SOURCE can be a named volume or a (relative or absolute) path on the host system. 
          #TARGET is an absolute path in the container where the volume is mounted. 
          #MODE is a mount option which can be read-only (ro) or read-write (rw) (default).
          #Example: ./data/alfresco/alf_data:/usr/local/tomcat/alf_data/:rw
          - ./data/alfresco/alf_data:/usr/local/tomcat/alf_data
          - ./logs/alfresco:/usr/local/tomcat/logs
        depends_on:
          - postgres
          - solr6
          
    transform-core-aio:
        image: alfresco/alfresco-transform-core-aio:${TRANSFORMATION_CORE_TAG}
        deploy:
          resources:
            limits:
              memory: 1536m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx1536m"
            TZ: "America/New_York"
        ports:
            - 8090:8090
            
    share:
        build:
          dockerfile: ./Dockerfile
          context: ./configs-to-override/share
          args:
            SHARE_TAG: ${SHARE_TAG}
        deploy:
          resources:
            limits:
              memory: 1g
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "7080"
            CATALINA_OPTS : "-agentlib:jdwp=transport=dt_socket,address=*:7000,server=y,suspend=n"
            JAVA_OPTS: "
                -Xms500m
                -Xmx500m
                -Dalfresco.host=localhost
                -Dalfresco.port=7080
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                "
            TZ: "America/New_York"
            
        volumes:
          - ./logs/share:/usr/local/tomcat/logs

    postgres:
        image: postgres:${POSTGRES_TAG}
        deploy:
          resources:
            limits:
              memory: 512m
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
            - TZ=America/New_York
        command: postgres -c max_connections=300 -c log_min_messages=LOG -p 5555
        ports:
            - 5555:5555
        volumes:
          - ./data/postgres/data:/var/lib/postgresql/data
          - ./logs/postgres:/var/log/postgresql
            
    solr6:
        image: alfresco/alfresco-search-services:${ASS_TAG}
        deploy:
          resources:
            limits:
              memory: 2g
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=7080
            #Solr jetty port, to start solr6 on port 9999
            - SOLR_PORT=9999
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=9999
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
            #HTTP by default
            - ALFRESCO_SECURE_COMMS=none
            - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"
            - TZ=America/New_York
        ports:
            - 8083:9999 #Browser port
        volumes:
            - ./data/search-services/data:/opt/alfresco-search-services/data
            
    activemq:
        image: alfresco/alfresco-activemq:${AMQ_TAG}
        deploy:
          resources:
            limits:
              memory: 1g
        environment:
            TZ: "America/New_York"
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP

    smtp:
        image: mwader/postfix-relay
        mem_limit: 128m
        
    proxy:
        build:
          dockerfile: ./Dockerfile
          context: ./configs-to-override/proxy
          args:
            NGNIX_TAG: ${NGNIX_TAG}
        deploy:
          resources:
            limits:
              memory: 256m
        depends_on:
            - alfresco
        environment:
            TZ: "America/New_York"
        ports:
            - 7080:7080
        links:
            - alfresco
            - share